import { useCallback, useEffect, useMemo, useState } from 'react';
import { UiPreferencesContext } from './uiPreferencesContextObject.js';

const STORAGE_KEY = 'securevote-ui-preferences';

const TRANSLATIONS = {
  en: {
    'app.skipToMain': 'Skip to main content',
    'nav.home': 'Home',
    'nav.candidates': 'Candidates',
    'nav.disputes': 'Disputes',
    'nav.manage': 'Manage',
    'nav.security': 'Security',
    'nav.transparency': 'Transparency',
    'nav.receipt': 'Receipt Verify',
    'nav.vote': 'Vote',
    'nav.logout': 'Logout',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'nav.toggleMenu': 'Toggle navigation menu',
    'nav.language': 'Language',
    'nav.theme': 'Theme',
    'nav.themeLight': 'Light mode on',
    'nav.themeDark': 'Dark mode on',
    'nav.accessibility': 'Accessibility',
    'nav.accessibilityOn': 'Accessibility mode on',
    'nav.accessibilityOff': 'Accessibility mode off',
    'nav.languageValue': 'English',
    'footer.platformNavigation': 'Platform Navigation',
    'footer.electionAccess': 'Election Access',
    'footer.trustSignals': 'Trust Signals',
    'footer.transparency': 'Transparency',
    'footer.verifyReceipt': 'Verify Receipt',
    'footer.castVote': 'Cast Vote',
    'footer.brandTitle': 'SecureVote Election Portal',
    'footer.brandSubtitle': 'Digital civic governance',
    'footer.brandBody': 'Built for high-trust public participation with secure authentication, controlled election lifecycles, and transparent vote accountability.',
    'footer.metric.multiElection': 'Multi-Election Ready',
    'footer.metric.receipt': 'Receipt Integrity',
    'footer.metric.public': 'Public Transparency',
    'footer.trustPoint.scope': 'Election-scoped ballots and candidate pools',
    'footer.trustPoint.oneVote': 'One vote per user per election enforcement',
    'footer.trustPoint.transparency': 'Public transparency metrics and receipt verification',
    'footer.copyright': 'Copyright {year} SecureVote Election Portal. Designed for transparent and auditable civic outcomes.',
    'security.title': 'Security Monitoring Center',
    'security.subtitle': 'Monitor anomaly signals across voter verification, vote bursts, and admin activity.',
    'security.na': 'N/A',
    'security.filters.severityAll': 'All Severity',
    'security.filters.eventAll': 'All Event Types',
    'security.filters.scope': 'Election Scope',
    'security.filters.severity': 'Severity',
    'security.filters.eventType': 'Event Type',
    'security.severity.low': 'Low',
    'security.severity.medium': 'Medium',
    'security.severity.high': 'High',
    'security.severity.critical': 'Critical',
    'security.loading': 'Loading security monitoring center...',
    'security.adminRequired': 'Admin Access Required',
    'security.adminOnly': 'This module is available only for election security administrators.',
    'security.eyebrow': 'Risk and Integrity Monitoring',
    'security.operator': 'Operator',
    'security.adminLabel': 'Admin',
    'security.totalEvents': 'Total Events',
    'security.totalAnomalies': 'Total Anomalies',
    'security.anomalies24h': '24h Anomalies',
    'security.noElections': 'No elections available',
    'security.selectElection': 'Select election',
    'security.recentAnomalies': 'Recent Anomalies',
    'security.loadingAnomalies': 'Loading anomaly feed...',
    'security.noAnomalies': 'No anomalies detected for the current filter scope.',
    'security.eventLabel': 'Event',
    'security.filteredStream': 'Filtered Event Stream',
    'security.loadingEvents': 'Loading event stream...',
    'security.noEvents': 'No events matched the selected filters.',
    'security.system': 'System',
    'home.hero.eyebrow': 'Public Decision Infrastructure',
    'home.hero.title': 'Secure digital voting with multi-election governance precision.',
    'home.hero.body': 'CivicBallot enables institutions to run multiple elections at once while preserving strict ballot scope, lifecycle control, transparent counting, and receipt-driven trust for every voter.',
    'home.hero.liveElections': 'Live Elections',
    'home.hero.trackedVotes': 'Tracked Votes',
    'home.hero.electionCandidates': 'Election Candidates',
    'home.hero.primaryCta': 'Create Voter Account',
    'home.hero.secondaryCta': 'Open Ballot Arena',
    'home.hero.linkCandidates': 'Candidate Profiles & Compare',
    'home.hero.linkTransparency': 'Public Transparency Dashboard',
    'home.hero.linkReceipt': 'Vote Receipt Verification',
    'home.hero.imageAlt': 'Citizens participating in a secure online voting ecosystem',
    'home.snapshot.title': 'Multi-Election Snapshot',
    'home.snapshot.registration': 'Registration',
    'home.snapshot.counting': 'Counting',
    'home.focus.title': 'Current Focus Election',
    'home.focus.status': 'Status',
    'home.focus.candidates': 'Candidates',
    'home.focus.votes': 'Votes',
    'home.focus.empty': 'No active election is available yet.',
    'home.standard.title': 'Governance Standard',
    'home.standard.body': 'Scoped ballots plus lifecycle controls create stronger democratic trust.',
    'home.stats.registeredVoters': 'Registered Voters',
    'home.stats.registeredHint': 'Identity-verified access',
    'home.stats.votesCast': 'Votes Cast',
    'home.stats.votesHint': 'Current election scope',
    'home.stats.activeElections': 'Active Elections',
    'home.stats.electionsHint': 'Concurrent civic tracks',
    'home.stats.turnout': 'Turnout',
    'home.stats.turnoutHint': 'Participation health',
    'home.steps.eyebrow': 'Steps To Use The Platform',
    'home.steps.title': 'A clear, citizen-first voting journey',
    'home.steps.subtitle': 'From registration to final vote confirmation, each step is designed for integrity, accessibility, and accountability.',
    'home.steps.step1.label': 'Step 01',
    'home.steps.step1.title': 'Register Securely',
    'home.steps.step1.body': 'Create your voter profile with verified identity details and secure credentials.',
    'home.steps.step2.label': 'Step 02',
    'home.steps.step2.title': 'Sign In & Verify',
    'home.steps.step2.body': 'Authenticate once and receive access to eligible election ballots.',
    'home.steps.step3.label': 'Step 03',
    'home.steps.step3.title': 'Cast Election-Scoped Vote',
    'home.steps.step3.body': 'Submit your decision per election context with strict one-vote enforcement.',
    'home.steps.step4.label': 'Step 04',
    'home.steps.step4.title': 'Verify Receipt Integrity',
    'home.steps.step4.body': 'Track your receipt status and validate election transparency in real time.',
    'home.lifecycle.title': 'Multi-Election Lifecycle',
    'home.lifecycle.subtitle': 'Every election follows a governed progression.',
    'home.lifecycle.body': 'The platform supports parallel elections while keeping each one independently scoped from setup to archive.',
    'home.lifecycle.elections': 'elections',
    'home.lifecycle.draft.title': 'Draft',
    'home.lifecycle.draft.description': 'Election administrators define scope, rules, and schedule windows.',
    'home.lifecycle.registration.title': 'Registration',
    'home.lifecycle.registration.description': 'Voter and candidate onboarding remains open before vote launch.',
    'home.lifecycle.live.title': 'Live Voting',
    'home.lifecycle.live.description': 'Citizens cast election-scoped ballots with receipt-backed confirmation.',
    'home.lifecycle.counting.title': 'Counting',
    'home.lifecycle.counting.description': 'Votes are aggregated while integrity checks are continuously applied.',
    'home.lifecycle.audited.title': 'Audited',
    'home.lifecycle.audited.description': 'Audit controls validate outcomes before final public publication.',
    'home.lifecycle.published.title': 'Published',
    'home.lifecycle.published.description': 'Election outcomes and transparency metrics are released for review.',
    'home.lifecycle.archived.title': 'Archived',
    'home.lifecycle.archived.description': 'Closed elections remain queryable for long-term governance records.',
    'home.why.eyebrow': 'Why Voting Is Needed',
    'home.why.title': 'Voting turns public needs into enforceable priorities.',
    'home.why.body': 'Elections are not a ritual. They are an accountability mechanism that determines who allocates budgets, writes policy, and represents citizen concerns. High-quality participation leads to better institutions.',
    'home.why.point1': 'Voting legitimizes public leadership through citizen consent.',
    'home.why.point2': 'It aligns public spending with real community priorities.',
    'home.why.point3': 'It creates peaceful transfer of power and policy continuity.',
    'home.evolution.eyebrow': 'Platform Evolution',
    'home.evolution.title': 'From one ballot to multi-election orchestration.',
    'home.evolution.body': 'A mature voting platform should reduce friction for voters while increasing confidence for regulators, observers, and election administrators.',
    'home.evolution.point1': 'One vote per user per election with separate receipt records.',
    'home.evolution.point2': 'Election-specific candidate pools and independent transparency metrics.',
    'home.evolution.point3': 'Lifecycle transitions from draft to archive with governance checkpoints.',
    'home.evolution.primaryCta': 'Join The Election',
    'home.evolution.secondaryCta': 'Explore Transparency',
    'vote.defaultVoter': 'Citizen',
    'vote.eyebrow': 'Official Ballot Arena',
    'vote.title': 'Cast Your Vote',
    'vote.welcome': 'Welcome',
    'vote.subtitle': 'Select one candidate and confirm your ballot.',
    'vote.accessibility.badge': 'Accessibility mode enabled',
    'vote.accessibility.stepperLabel': 'Voting steps',
    'vote.accessibility.stepStatus': 'Step {current} of {total}',
    'vote.accessibility.instructions': 'Use Tab to move between fields and buttons. Press Enter or Space to activate.',
    'vote.accessibility.stepElection': 'Choose election',
    'vote.accessibility.stepCandidate': 'Select candidate',
    'vote.accessibility.stepVerification': 'Verify identity',
    'vote.accessibility.stepReview': 'Review & submit',
    'vote.accessibility.back': 'Back',
    'vote.accessibility.next': 'Continue',
    'vote.accessibility.candidateHint': 'Choose one candidate. Use Tab to move through the options.',
    'vote.accessibility.verificationHint': 'Request a 6-digit code and verify it to unlock submission.',
    'vote.accessibility.reviewHint': 'Review your selection and confirm the voting terms before submitting.',
    'vote.statusTitle': 'Voting Status',
    'vote.status.submitted': 'Vote already submitted',
    'vote.status.awaiting': 'Awaiting your vote',
    'vote.selectElection': 'Select Election',
    'vote.selectElectionPlaceholder': 'Select election',
    'vote.noElections': 'No elections available',
    'vote.metric.candidates': 'Candidates',
    'vote.metric.votes': 'Election Votes',
    'vote.metric.electionCandidates': 'Election Candidates',
    'vote.loading': 'Loading official ballot data...',
    'vote.noElectionTitle': 'No election is available',
    'vote.noElectionBody': 'Admin can create an election first, then voting will be enabled.',
    'vote.loadingBallot': 'Loading selected election ballot...',
    'vote.noCandidatesTitle': 'No candidates available',
    'vote.noCandidatesBody': 'Candidates have not been configured for this election yet.',
    'vote.summary.title': 'Vote Summary',
    'vote.summary.imageAlt': 'Digital ballot and secure vote confirmation',
    'vote.summary.election': 'Election',
    'vote.summary.selectedCandidate': 'Selected Candidate',
    'vote.summary.noneSelected': 'No candidate selected yet.',
    'vote.summary.oneVote': 'One account can cast only one vote per election. Review your selection carefully before submitting.',
    'vote.verification.title': 'Strong Voter Verification',
    'vote.verification.body': 'Request a one-time 6-digit code, verify it, then submit your ballot.',
    'vote.verification.requesting': 'Requesting...',
    'vote.verification.request': 'Request Code',
    'vote.verification.placeholder': '6-digit code',
    'vote.verification.verifying': 'Verifying...',
    'vote.verification.verify': 'Verify Code',
    'vote.verification.preview': 'Dev preview code',
    'vote.verification.expires': 'Code expires at',
    'vote.verification.active': 'Verification active for this election.',
    'vote.terms': 'I confirm this vote is my independent and final decision.',
    'vote.cta.submitting': 'Submitting vote...',
    'vote.cta.submitted': 'Vote Already Submitted',
    'vote.cta.notLive': 'Election Not Live',
    'vote.cta.completeVerification': 'Complete Verification First',
    'vote.cta.confirm': 'Confirm Vote',
    'vote.footerNote': 'Submission is protected by authenticated session and single-vote enforcement.',
    'vote.recorded': 'Your vote has been successfully recorded.',
    'vote.receipt.title': 'Vote Receipt',
    'vote.receipt.verify': 'Verify This Receipt',
    'vote.errors.loadElections': 'Unable to load election data. Please refresh and try again.',
    'vote.errors.loadReceipt': 'Unable to load receipt status for this election.',
    'vote.errors.loadBallot': 'Unable to load ballot data for this election. Please try again.',
    'vote.errors.selectElectionForCode': 'Select an election before requesting verification code.',
    'vote.errors.verificationNotLive': 'Verification is available only while election status is live.',
    'vote.errors.alreadyVoted': 'Vote is already cast for this election.',
    'vote.verification.requested': 'Verification code requested successfully.',
    'vote.errors.requestCodeFailed': 'Could not request verification code.',
    'vote.errors.invalidCode': 'Enter a valid 6-digit verification code.',
    'vote.verification.success': 'Verification completed. You can now cast your vote.',
    'vote.errors.verifyFailed': 'Code verification failed.',
    'vote.errors.selectElection': 'Select an election before voting.',
    'vote.errors.notLive': 'This election is not currently accepting votes.',
    'vote.errors.confirmTerms': 'Please confirm the voting terms to continue',
    'vote.errors.selectCandidate': 'Please select one candidate to continue',
    'vote.errors.completeVerification': 'Complete strong voter verification before submitting your vote.',
    'vote.success': 'Vote submitted successfully!',
    'vote.errors.submitFailed': 'Failed to submit vote. Please try again.',
    'vote.statusLabel': 'Status',
    'election.status.unknown': 'Unknown',
    'election.status.draft': 'Draft',
    'election.status.registration': 'Registration',
    'election.status.live': 'Voting Live',
    'election.status.counting': 'Counting',
    'election.status.audited': 'Audited',
    'election.status.published': 'Published',
    'election.status.archived': 'Archived',
    'candidates.eyebrow': 'Candidate Profiles + Compare',
    'candidates.title': 'Explore Candidates Deeply',
    'candidates.subtitle': 'Review verified candidate profiles and compare up to three candidates side-by-side before entering the ballot arena.',
    'candidates.electionContext': 'Election Context',
    'candidates.noElections': 'No elections available',
    'candidates.selectElection': 'Select election',
    'candidates.imageAlt': 'Candidate comparison board',
    'candidates.noElectionSelected': 'No election selected',
    'candidates.stats.election': 'Election',
    'candidates.stats.visible': 'Visible Candidates',
    'candidates.stats.parties': 'Participating Parties',
    'candidates.stats.compareQueue': 'Compare Queue',
    'candidates.searchPlaceholder': 'Search by candidate, party, region, or manifesto',
    'candidates.loading': 'Loading candidate profiles...',
    'candidates.none': 'No candidates found for this election.',
    'candidates.verified': 'Verified',
    'candidates.profileOpen': 'Profile Open',
    'candidates.viewProfile': 'View Profile',
    'candidates.removeCompare': 'Remove Compare',
    'candidates.addCompare': 'Add To Compare',
    'candidates.profile.title': 'Candidate Profile',
    'candidates.profile.loading': 'Loading profile...',
    'candidates.profile.empty': 'Pick any candidate to view a full profile.',
    'candidates.profile.region': 'Region',
    'candidates.profile.education': 'Education',
    'candidates.profile.experience': 'Experience',
    'candidates.profile.na': 'N/A',
    'candidates.compare.title': 'Compare Board',
    'candidates.compare.reset': 'Reset',
    'candidates.compare.instructions': 'Select 2 to 3 candidates for side-by-side comparison.',
    'candidates.compare.noneSelected': 'No candidates selected.',
    'candidates.compare.selected': 'Selected',
    'candidates.compare.loading': 'Loading comparison...',
    'candidates.compare.field': 'Field',
    'candidates.compare.party': 'Party',
    'candidates.compare.region': 'Region',
    'candidates.compare.experience': 'Experience',
    'candidates.compare.priorities': 'Priorities',
    'candidates.compare.empty': 'Comparison table appears once you select at least 2 candidates.',
    'candidates.compare.cta': 'Continue To Ballot',
    'candidates.region.district': '{region} District',
    'candidates.region.national': 'National Civic District',
    'candidates.experience.double': 'Policy leadership in {area1} and {area2}',
    'candidates.experience.single': 'Policy leadership in {area}',
    'candidates.experience.default': 'Public administration and civic policy leadership',
    'candidates.priorities.citizenService': 'Citizen service delivery',
    'candidates.priorities.accountability': 'Policy accountability',
    'candidates.priorities.transparent': 'Transparent governance',
    'candidates.errors.loadElections': 'Unable to load elections. Please try again.',
    'candidates.errors.loadCandidates': 'Unable to load candidate profiles for this election. Please try again.',
    'candidates.errors.compareFailed': 'Failed to load comparison data.',
    'candidates.errors.compareLimit': 'You can compare up to 3 candidates at once.',
    'transparency.errors.load': 'Unable to load transparency dashboard right now.',
    'transparency.eyebrow': 'Public Transparency Dashboard',
    'transparency.title': 'Open Election Metrics',
    'transparency.subtitle': 'Real-time visibility into turnout, candidate rankings, party vote share, and receipt-level verification activity.',
    'transparency.scope': 'Election Scope',
    'transparency.noElections': 'No elections available',
    'transparency.selectElection': 'Select election',
    'transparency.metrics.parties': 'Parties',
    'transparency.metrics.ranked': 'Ranked Candidates',
    'transparency.metrics.receipts': 'Recent Receipts',
    'transparency.imageAlt': 'Election transparency analytics',
    'transparency.loading': 'Loading transparency metrics...',
    'transparency.empty': 'No election is available for transparency analytics yet.',
    'transparency.table.election': 'Election',
    'transparency.table.registered': 'Registered Voters',
    'transparency.table.votes': 'Votes Cast',
    'transparency.table.turnout': 'Turnout',
    'transparency.table.parties': 'Active Parties',
    'transparency.results.title': 'Election Result Calculation',
    'transparency.results.subtitle': 'Each election below shows the top 3 candidates and total votes cast for dynamic result tracking.',
    'transparency.results.empty': 'No election result data available yet.',
    'transparency.results.totalVotes': 'Total Votes Cast',
    'transparency.results.rank': 'Rank',
    'transparency.results.candidate': 'Candidate',
    'transparency.results.party': 'Party',
    'transparency.results.votes': 'Votes',
    'transparency.chart.partyShare': 'Party Vote Share',
    'transparency.chart.empty': 'No party vote share data available.',
    'transparency.chart.votes': 'votes',
    'transparency.timeline.title': 'Turnout Timeline',
    'transparency.timeline.empty': 'No turnout events recorded yet.',
    'login.eyebrow': 'Secure Sign In',
    'login.title': 'Welcome Back',
    'login.subtitle': 'Access your verified ballot and participate in official decision-making.',
    'login.badge.jwt': 'JWT Session',
    'login.badge.oneVote': 'One Vote / Election',
    'login.badge.receipt': 'Receipt Backed',
    'login.emailLabel': 'Email Address',
    'login.emailPlaceholder': 'you@example.com',
    'login.passwordLabel': 'Password',
    'login.passwordPlaceholder': 'Enter your secure password',
    'login.loading': 'Signing in...',
    'login.cta': 'Sign In',
    'login.noAccount': 'New voter?',
    'login.createAccount': 'Create an account',
    'login.imageAlt': 'Secure voter login with shield and lock protection',
    'login.assuranceEyebrow': 'Platform Assurance',
    'login.assuranceTitle': 'Election-grade access controls',
    'login.assuranceBody': 'Session protection, token-based authentication, and single-vote enforcement preserve institutional trust.',
    'login.assurance.identityTitle': 'Identity Verification',
    'login.assurance.identityBody': 'Only authenticated users can access the ballot interface.',
    'login.assurance.sessionTitle': 'Session Security',
    'login.assurance.sessionBody': 'Authenticated state is synced across the app for controlled access.',
    'login.assurance.readyTitle': 'Governance Ready',
    'login.assurance.readyBody': 'A refined citizen experience built for credible public participation.',
    'login.success': 'Login successful! Redirecting...',
    'login.error': 'Login failed. Please try again.',
    'signup.eyebrow': 'Verified Registration',
    'signup.title': 'Create Voter Account',
    'signup.subtitle': 'Register once to access your official digital ballot and governance dashboard.',
    'signup.badge.identity': 'Identity Ready',
    'signup.badge.credential': 'Secure Credential',
    'signup.badge.access': 'Instant Ballot Access',
    'signup.nameLabel': 'Full Name',
    'signup.namePlaceholder': 'Your full legal name',
    'signup.emailLabel': 'Email Address',
    'signup.emailPlaceholder': 'you@example.com',
    'signup.passwordLabel': 'Password',
    'signup.passwordPlaceholder': 'At least 6 characters',
    'signup.confirmLabel': 'Confirm Password',
    'signup.confirmPlaceholder': 'Re-enter password',
    'signup.loading': 'Creating account...',
    'signup.cta': 'Create Account',
    'signup.haveAccount': 'Already registered?',
    'signup.signInLink': 'Sign in here',
    'signup.imageAlt': 'Citizen onboarding and identity verification for voting platform',
    'signup.onboardingEyebrow': 'Onboarding Standards',
    'signup.onboardingTitle': 'Trusted civic onboarding',
    'signup.onboardingBody': 'A mature voting ecosystem starts with clean registration, identity confidence, and fraud-resistant account creation.',
    'signup.onboarding.identityTitle': 'Citizen Identity Ready',
    'signup.onboarding.identityBody': 'Users are onboarded before they can access ballots.',
    'signup.onboarding.credentialsTitle': 'Protected Credentials',
    'signup.onboarding.credentialsBody': 'Passwords are validated before account creation is accepted.',
    'signup.onboarding.ballotTitle': 'Direct Ballot Access',
    'signup.onboarding.ballotBody': 'After registration, users move directly to the secure voting arena.',
    'signup.onboarding.integrityTitle': 'Platform Integrity',
    'signup.onboarding.integrityBody': 'Reliable onboarding is the first layer of election credibility.',
    'signup.success': 'Account created successfully! Redirecting...',
    'signup.errors.passwordMismatch': 'Passwords do not match',
    'signup.errors.passwordLength': 'Password must be at least 6 characters',
    'signup.errors.submitFailed': 'Registration failed. Please try again.',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.refresh': 'Refresh',
    'common.na': 'N/A',
    'common.ellipsis': '...',
    'manage.errors.loadCandidates': 'Unable to load candidate management data.',
    'manage.errors.adminOnly': 'Candidate and election management is restricted to admin accounts only.',
    'manage.errors.loadAdmin': 'Unable to load admin management data.',
    'manage.errors.candidateAdminOnly': 'Candidate management is restricted to admin accounts only.',
    'manage.errors.selectElectionForCandidate': 'Select an election before managing candidates.',
    'manage.errors.candidateRequiredFields': 'Name, party, and manifesto are required.',
    'manage.toast.candidateUpdated': 'Candidate updated successfully.',
    'manage.toast.candidateCreated': 'Candidate created successfully.',
    'manage.errors.saveCandidate': 'Failed to save candidate.',
    'manage.toast.candidateDeleted': 'Candidate removed successfully.',
    'manage.errors.deleteCandidate': 'Failed to delete candidate.',
    'manage.errors.electionAdminOnly': 'Election management is restricted to admin accounts only.',
    'manage.errors.electionNameRequired': 'Election name is required.',
    'manage.toast.electionUpdated': 'Election updated successfully.',
    'manage.toast.electionCreated': 'Election created successfully.',
    'manage.errors.saveElection': 'Failed to save election.',
    'manage.toast.electionTransition': 'Election moved to {status}.',
    'manage.errors.transitionElection': 'Failed to transition election status.',
    'manage.modal.deleteCandidateTitle': 'Delete Candidate',
    'manage.modal.deleteCandidateBody': 'Delete this candidate? This action cannot be undone.',
    'manage.header.eyebrow': 'Election + Candidate Management',
    'manage.header.title': 'Run Election Lifecycle Operations',
    'manage.header.subtitle': 'Create elections, move lifecycle states, and manage candidate records per election context.',
    'manage.metrics.totalElections': 'Total Elections',
    'manage.metrics.liveElections': 'Live Elections',
    'manage.metrics.registeredCandidates': 'Registered Candidates',
    'manage.metrics.trackedVotes': 'Tracked Votes',
    'manage.state.loadingWorkspace': 'Loading admin management workspace...',
    'manage.state.restrictedTitle': 'Restricted Access',
    'manage.state.restrictedBody': 'Election and candidate management is available only for admin accounts.',
    'manage.elections.title': 'Election Lifecycle Studio',
    'manage.elections.form.name': 'Election Name',
    'manage.elections.form.namePlaceholder': 'National General Election 2027',
    'manage.elections.form.description': 'Description',
    'manage.elections.form.descriptionPlaceholder': 'Optional election description',
    'manage.elections.form.registrationStarts': 'Registration Starts',
    'manage.elections.form.registrationEnds': 'Registration Ends',
    'manage.elections.form.votingStarts': 'Voting Starts',
    'manage.elections.form.votingEnds': 'Voting Ends',
    'manage.elections.form.update': 'Update Election',
    'manage.elections.form.create': 'Create Election',
    'manage.elections.form.cancelEdit': 'Cancel Edit',
    'manage.elections.empty': 'No elections created yet.',
    'manage.elections.card.status': 'Status: {status}',
    'manage.elections.card.stats': 'Candidates: {candidates} | Votes: {votes}',
    'manage.elections.card.selected': 'Selected',
    'manage.elections.card.select': 'Select',
    'manage.elections.card.transitioning': 'Transitioning...',
    'manage.elections.card.moveTo': 'Move to {status}',
    'manage.candidates.title': 'Candidate Studio',
    'manage.candidates.activeElection': 'Active Election',
    'manage.candidates.noElections': 'No elections available',
    'manage.candidates.selectElection': 'Select election',
    'manage.candidates.lifecycle': 'Lifecycle: {status}',
    'manage.candidates.form.name': 'Candidate Name',
    'manage.candidates.form.namePlaceholder': 'Full name',
    'manage.candidates.form.party': 'Party',
    'manage.candidates.form.partyPlaceholder': 'Party name',
    'manage.candidates.form.tagline': 'Campaign Tagline',
    'manage.candidates.form.taglinePlaceholder': 'Short campaign line',
    'manage.candidates.form.region': 'Region',
    'manage.candidates.form.regionPlaceholder': 'Region or district',
    'manage.candidates.form.experience': 'Experience',
    'manage.candidates.form.experiencePlaceholder': 'Experience summary',
    'manage.candidates.form.imageUrl': 'Image URL',
    'manage.candidates.form.imageUrlPlaceholder': 'https://example.com/candidate.jpg',
    'manage.candidates.form.manifesto': 'Manifesto',
    'manage.candidates.form.manifestoPlaceholder': 'Candidate manifesto',
    'manage.candidates.form.priorities': 'Priorities (comma separated)',
    'manage.candidates.form.prioritiesPlaceholder': 'Healthcare, education, transport',
    'manage.candidates.form.update': 'Update Candidate',
    'manage.candidates.form.add': 'Add Candidate',
    'manage.candidates.form.cancelEdit': 'Cancel Edit',
    'manage.candidates.loading': 'Loading candidates...',
    'manage.candidates.empty': 'No candidates available for this election yet.',
    'manage.candidates.card.votes': 'Votes: {count}',
    'disputes.status.open': 'Open',
    'disputes.status.underReview': 'Under Review',
    'disputes.status.resolved': 'Resolved',
    'disputes.status.rejected': 'Rejected',
    'disputes.type.recount': 'Recount',
    'disputes.type.dispute': 'Dispute',
    'disputes.form.type.disputeCase': 'Dispute Case',
    'disputes.form.type.recountRequest': 'Recount Request',
    'disputes.filters.status.all': 'All Statuses',
    'disputes.filters.type.all': 'All Types',
    'disputes.errors.bootstrap': 'Unable to load recount and dispute module right now.',
    'disputes.errors.loadMyCases': 'Could not load your dispute records.',
    'disputes.errors.loadAdminCases': 'Could not load admin dispute queue.',
    'disputes.errors.selectElection': 'Select an election before filing a case.',
    'disputes.errors.subjectLength': 'Subject must be at least 8 characters.',
    'disputes.errors.descriptionLength': 'Description must be at least 20 characters.',
    'disputes.errors.recountNeedsEvidence': 'Recount requests require a receipt code or candidate selection.',
    'disputes.toast.caseSubmitted': 'Case submitted successfully.',
    'disputes.errors.submitCase': 'Failed to submit dispute case.',
    'disputes.errors.resolutionNoteLength': 'Add at least 10 characters in resolution note for final updates.',
    'disputes.toast.caseStatusUpdated': 'Case marked as {status}.',
    'disputes.errors.updateStatus': 'Could not update case status.',
    'disputes.header.eyebrow': 'Recount and Dispute Module',
    'disputes.header.title': 'Election Case Management',
    'disputes.header.subtitle': 'File recount requests and integrity disputes in a separate workflow, then track case review and outcomes.',
    'disputes.imageAlt': 'Dispute resolution dashboard illustration',
    'disputes.metrics.role': 'Role: {role}',
    'disputes.metrics.totalCases': 'Election Cases: {count}',
    'disputes.metrics.currentElection': 'Current Election: {name}',
    'disputes.metrics.notSelected': 'Not selected',
    'disputes.state.loadingModule': 'Loading module...',
    'disputes.filters.electionScope': 'Election Scope',
    'disputes.filters.noElections': 'No elections available',
    'disputes.filters.selectElection': 'Select election',
    'disputes.filters.status.label': 'Status Filter',
    'disputes.filters.type.label': 'Type Filter',
    'disputes.form.title': 'File New Case',
    'disputes.form.type.label': 'Case Type',
    'disputes.form.candidate.label': 'Candidate (Optional)',
    'disputes.form.candidate.placeholder': 'Select candidate',
    'disputes.form.subject.label': 'Subject',
    'disputes.form.subject.placeholder': 'Example: Request recount for receipt mismatch',
    'disputes.form.receipt.label': 'Receipt Code (Optional)',
    'disputes.form.receipt.placeholder': 'CV-2026-AB12EF',
    'disputes.form.description.label': 'Description',
    'disputes.form.description.placeholder': 'Describe what happened, why recount or investigation is needed, and relevant timeline details.',
    'disputes.form.candidate.linked': 'Candidate linked to this case:',
    'disputes.form.submitting': 'Submitting...',
    'disputes.form.submit': 'Submit Case',
    'disputes.myCases.title': 'My Cases',
    'disputes.myCases.loading': 'Loading your cases...',
    'disputes.myCases.empty': 'No case records found for the selected election.',
    'disputes.myCases.type': 'Type: {type}',
    'disputes.myCases.receipt': 'Receipt: {code}',
    'disputes.myCases.filed': 'Filed: {date}',
    'disputes.myCases.resolutionNote': 'Resolution Note',
    'disputes.admin.title': 'Admin Review Queue',
    'disputes.admin.refresh': 'Refresh Queue',
    'disputes.admin.loading': 'Loading admin queue...',
    'disputes.admin.empty': 'No dispute cases match the selected filters.',
    'disputes.admin.filedBy': '{election} | Filed by {name}',
    'disputes.admin.filedByFallback': 'Voter',
    'disputes.admin.resolutionPlaceholder': 'Add investigation findings or final resolution note',
    'disputes.admin.actions.underReview': 'Mark Under Review',
    'disputes.admin.actions.resolve': 'Resolve',
    'disputes.admin.actions.reject': 'Reject',
    'disputes.notes.title': 'Workflow Notes',
    'disputes.notes.item1': 'Use Dispute for ballot integrity, eligibility, or system behavior issues.',
    'disputes.notes.item2': 'Use Recount when tally confidence needs a candidate- or receipt-linked review.',
    'disputes.notes.item3': 'Case statuses update from Open to Under Review, then Resolved or Rejected.',
    'disputes.notes.item4': 'You can track final notes and actions in the My Cases panel.',
    'disputes.notes.footer': 'Case records are linked to election scope for transparent auditing.',
    'receipt.header.eyebrow': 'Vote Receipt Verification',
    'receipt.header.title': 'Verify Vote Integrity',
    'receipt.header.subtitle': 'Confirm that a vote receipt exists in the election ledger by entering a receipt code generated at vote submission.',
    'receipt.header.imageAlt': 'Vote receipt verification dashboard',
    'receipt.metrics.ledgerSearch': 'Ledger Search',
    'receipt.metrics.electionScoped': 'Election Scoped',
    'receipt.metrics.pdfExport': 'PDF Export',
    'receipt.controls.placeholder': 'Enter receipt code (e.g., CV-2026-AB12EF)',
    'receipt.controls.verifying': 'Verifying...',
    'receipt.controls.verify': 'Verify',
    'receipt.controls.exportPdf': 'Export PDF',
    'receipt.controls.electionScope': 'Election Scope (For My Receipt)',
    'receipt.controls.noElections': 'No elections available',
    'receipt.controls.selectElection': 'Select election',
    'receipt.controls.exportHint': 'Export becomes available when voter details and at least one receipt record are loaded.',
    'receipt.myReceipt.title': 'My Receipt',
    'receipt.myReceipt.loading': 'Loading your receipt...',
    'receipt.myReceipt.cardTitle': 'Authenticated Voter Receipt',
    'receipt.myReceipt.empty': 'Sign in and cast your vote to generate a personal receipt code.',
    'receipt.verify.title': 'Verification Result',
    'receipt.verify.loading': 'Verifying receipt in ledger...',
    'receipt.verify.success': 'Receipt verified successfully',
    'receipt.verify.cardTitle': 'Ledger Verification',
    'receipt.verify.empty': 'Enter a receipt code to verify vote submission status.',
    'receipt.card.code': 'Receipt Code',
    'receipt.card.status': 'Status',
    'receipt.card.submitted': 'Submitted At',
    'receipt.card.candidate': 'Candidate',
    'receipt.card.candidateMissing': 'Candidate not available',
    'receipt.errors.fetchMine': 'Could not fetch your receipt right now.',
    'receipt.errors.invalidCode': 'Please enter a valid receipt code.',
    'receipt.errors.verifyFailed': 'Unable to verify receipt right now.',
    'receipt.pdf.notAvailable': 'Not available',
    'receipt.pdf.portalTitle': 'SecureVote Election Portal',
    'receipt.pdf.issued': 'Document Issued: {date}',
    'receipt.pdf.reportTitle': 'Vote Integrity Export Report',
    'receipt.pdf.voterDetails': 'Voter Details',
    'receipt.pdf.name': 'Name: {name}',
    'receipt.pdf.email': 'Email: {email}',
    'receipt.pdf.role': 'Role: {role}',
    'receipt.pdf.roleFallback': 'Voter',
    'receipt.pdf.votingStatus': 'Voting Status: {status}',
    'receipt.pdf.voteCast': 'Vote Cast',
    'receipt.pdf.notCast': 'Not Cast Yet',
    'receipt.pdf.voteReceiptDetails': 'Vote / Receipt Details',
    'receipt.pdf.election': 'Election: {name}',
    'receipt.pdf.receiptCode': 'Receipt Code: {code}',
    'receipt.pdf.receiptStatus': 'Receipt Status: {status}',
    'receipt.pdf.submittedAt': 'Submitted At: {date}',
    'receipt.pdf.candidate': 'Candidate: {name}',
    'receipt.pdf.candidateMissing': 'Candidate not available',
    'receipt.pdf.footer': 'This report is generated from the vote integrity dashboard and is intended for record keeping.'
  },
  hi: {
    'app.skipToMain': 'मुख्य सामग्री पर जाएं',
    'nav.home': 'होम',
    'nav.candidates': 'उम्मीदवार',
    'nav.disputes': 'विवाद',
    'nav.manage': 'प्रबंधन',
    'nav.security': 'सुरक्षा',
    'nav.transparency': 'पारदर्शिता',
    'nav.receipt': 'रसीद जाँच',
    'nav.vote': 'वोट',
    'nav.logout': 'लॉगआउट',
    'nav.login': 'लॉगिन',
    'nav.register': 'रजिस्टर',
    'nav.toggleMenu': 'नेविगेशन मेनू टॉगल करें',
    'nav.language': 'भाषा',
    'nav.theme': 'थीम',
    'nav.themeLight': 'लाइट मोड चालू',
    'nav.themeDark': 'डार्क मोड चालू',
    'nav.accessibility': 'सुलभता',
    'nav.accessibilityOn': 'सुलभता मोड चालू',
    'nav.accessibilityOff': 'सुलभता मोड बंद',
    'nav.languageValue': 'हिंदी',
    'footer.platformNavigation': 'प्लेटफॉर्म नेविगेशन',
    'footer.electionAccess': 'चुनाव एक्सेस',
    'footer.trustSignals': 'विश्वास संकेत',
    'footer.transparency': 'पारदर्शिता',
    'footer.verifyReceipt': 'रसीद जाँच',
    'footer.castVote': 'वोट करें',
    'footer.brandTitle': 'SecureVote चुनाव पोर्टल',
    'footer.brandSubtitle': 'डिजिटल नागरिक गवर्नेंस',
    'footer.brandBody': 'उच्च भरोसे वाली सार्वजनिक भागीदारी के लिए सुरक्षित प्रमाणीकरण, नियंत्रित चुनाव लाइफसाइकिल और पारदर्शी वोट जवाबदेही।',
    'footer.metric.multiElection': 'बहु-चुनाव तैयार',
    'footer.metric.receipt': 'रसीद अखंडता',
    'footer.metric.public': 'सार्वजनिक पारदर्शिता',
    'footer.trustPoint.scope': 'चुनाव-स्कोप्ड बैलट और उम्मीदवार समूह',
    'footer.trustPoint.oneVote': 'प्रति चुनाव प्रति यूजर एक वोट प्रवर्तन',
    'footer.trustPoint.transparency': 'सार्वजनिक पारदर्शिता मेट्रिक्स और रसीद सत्यापन',
    'footer.copyright': 'कॉपीराइट {year} SecureVote चुनाव पोर्टल। पारदर्शी और ऑडिट योग्य नागरिक परिणामों के लिए डिजाइन किया गया।',
    'security.title': 'सुरक्षा मॉनिटरिंग केंद्र',
    'security.subtitle': 'वोटर वेरिफिकेशन, वोट बर्स्ट और एडमिन गतिविधि पर विसंगति संकेत देखें।',
    'security.na': 'उपलब्ध नहीं',
    'security.filters.severityAll': 'सभी गंभीरता',
    'security.filters.eventAll': 'सभी इवेंट प्रकार',
    'security.filters.scope': 'चुनाव स्कोप',
    'security.filters.severity': 'गंभीरता',
    'security.filters.eventType': 'इवेंट प्रकार',
    'security.severity.low': 'कम',
    'security.severity.medium': 'मध्यम',
    'security.severity.high': 'उच्च',
    'security.severity.critical': 'गंभीर',
    'security.loading': 'सुरक्षा मॉनिटरिंग केंद्र लोड हो रहा है...',
    'security.adminRequired': 'एडमिन एक्सेस आवश्यक',
    'security.adminOnly': 'यह मॉड्यूल केवल चुनाव सुरक्षा प्रशासकों के लिए उपलब्ध है।',
    'security.eyebrow': 'जोखिम और अखंडता मॉनिटरिंग',
    'security.operator': 'ऑपरेटर',
    'security.adminLabel': 'एडमिन',
    'security.totalEvents': 'कुल इवेंट',
    'security.totalAnomalies': 'कुल विसंगतियां',
    'security.anomalies24h': '24 घंटे की विसंगतियां',
    'security.noElections': 'कोई चुनाव उपलब्ध नहीं',
    'security.selectElection': 'चुनाव चुनें',
    'security.recentAnomalies': 'हाल की विसंगतियां',
    'security.loadingAnomalies': 'विसंगति फ़ीड लोड हो रही है...',
    'security.noAnomalies': 'वर्तमान फिल्टर स्कोप में कोई विसंगति नहीं मिली।',
    'security.eventLabel': 'इवेंट',
    'security.filteredStream': 'फ़िल्टर किया गया इवेंट स्ट्रीम',
    'security.loadingEvents': 'इवेंट स्ट्रीम लोड हो रहा है...',
    'security.noEvents': 'चयनित फ़िल्टर के लिए कोई इवेंट नहीं मिला।',
    'security.system': 'सिस्टम',
    'home.hero.eyebrow': 'सार्वजनिक निर्णय अवसंरचना',
    'home.hero.title': 'बहु-चुनावी शासन के साथ सुरक्षित डिजिटल मतदान।',
    'home.hero.body': 'CivicBallot कई चुनाव एक साथ चलाने देता है और सख्त बैलट स्कोप, लाइफसाइकिल नियंत्रण, पारदर्शी गिनती, और हर वोटर के लिए रसीद आधारित भरोसा सुनिश्चित करता है।',
    'home.hero.liveElections': 'लाइव चुनाव',
    'home.hero.trackedVotes': 'ट्रैक किए गए वोट',
    'home.hero.electionCandidates': 'चुनावी उम्मीदवार',
    'home.hero.primaryCta': 'वोटर अकाउंट बनाएं',
    'home.hero.secondaryCta': 'बैलट एरिना खोलें',
    'home.hero.linkCandidates': 'उम्मीदवार प्रोफाइल और तुलना',
    'home.hero.linkTransparency': 'सार्वजनिक पारदर्शिता डैशबोर्ड',
    'home.hero.linkReceipt': 'वोट रसीद सत्यापन',
    'home.hero.imageAlt': 'सुरक्षित ऑनलाइन वोटिंग इकोसिस्टम में नागरिक',
    'home.snapshot.title': 'बहु-चुनाव स्नैपशॉट',
    'home.snapshot.registration': 'पंजीकरण',
    'home.snapshot.counting': 'गिनती',
    'home.focus.title': 'वर्तमान फोकस चुनाव',
    'home.focus.status': 'स्थिति',
    'home.focus.candidates': 'उम्मीदवार',
    'home.focus.votes': 'वोट',
    'home.focus.empty': 'अभी कोई सक्रिय चुनाव उपलब्ध नहीं है।',
    'home.standard.title': 'गवर्नेंस मानक',
    'home.standard.body': 'स्कोप्ड बैलट और लाइफसाइकिल नियंत्रण मजबूत लोकतांत्रिक भरोसा बनाते हैं।',
    'home.stats.registeredVoters': 'पंजीकृत वोटर',
    'home.stats.registeredHint': 'पहचान- सत्यापित प्रवेश',
    'home.stats.votesCast': 'कुल वोट',
    'home.stats.votesHint': 'वर्तमान चुनाव स्कोप',
    'home.stats.activeElections': 'सक्रिय चुनाव',
    'home.stats.electionsHint': 'समांतर नागरिक ट्रैक',
    'home.stats.turnout': 'मतदान प्रतिशत',
    'home.stats.turnoutHint': 'भागीदारी स्वास्थ्य',
    'home.steps.eyebrow': 'प्लेटफॉर्म उपयोग के चरण',
    'home.steps.title': 'स्पष्ट, नागरिक-प्रथम मतदान यात्रा',
    'home.steps.subtitle': 'पंजीकरण से अंतिम पुष्टि तक हर चरण अखंडता, पहुंच, और जवाबदेही के लिए डिजाइन किया गया है।',
    'home.steps.step1.label': 'चरण 01',
    'home.steps.step1.title': 'सुरक्षित पंजीकरण',
    'home.steps.step1.body': 'सत्यापित पहचान विवरण और सुरक्षित क्रेडेंशियल के साथ वोटर प्रोफाइल बनाएं।',
    'home.steps.step2.label': 'चरण 02',
    'home.steps.step2.title': 'साइन इन और सत्यापन',
    'home.steps.step2.body': 'एक बार प्रमाणीकरण करें और योग्य चुनाव बैलट तक पहुंच पाएं।',
    'home.steps.step3.label': 'चरण 03',
    'home.steps.step3.title': 'चुनाव-स्कोप्ड वोट डालें',
    'home.steps.step3.body': 'प्रत्येक चुनाव संदर्भ के अनुसार निर्णय सबमिट करें और एक वोट नियम लागू रखें।',
    'home.steps.step4.label': 'चरण 04',
    'home.steps.step4.title': 'रसीद अखंडता सत्यापित करें',
    'home.steps.step4.body': 'रसीद स्थिति ट्रैक करें और चुनाव पारदर्शिता रियल टाइम में देखें।',
    'home.lifecycle.title': 'बहु-चुनाव लाइफसाइकिल',
    'home.lifecycle.subtitle': 'हर चुनाव एक नियंत्रित क्रम का पालन करता है।',
    'home.lifecycle.body': 'प्लेटफॉर्म समानांतर चुनावों को समर्थन देता है और हर चुनाव को सेटअप से आर्काइव तक अलग स्कोप में रखता है।',
    'home.lifecycle.elections': 'चुनाव',
    'home.lifecycle.draft.title': 'ड्राफ्ट',
    'home.lifecycle.draft.description': 'प्रशासक स्कोप, नियम, और समय-सीमा तय करते हैं।',
    'home.lifecycle.registration.title': 'पंजीकरण',
    'home.lifecycle.registration.description': 'वोटर और उम्मीदवार ऑनबोर्डिंग वोट लॉन्च से पहले खुली रहती है।',
    'home.lifecycle.live.title': 'लाइव मतदान',
    'home.lifecycle.live.description': 'नागरिक रसीद-आधारित पुष्टि के साथ चुनाव-स्कोप्ड बैलट डालते हैं।',
    'home.lifecycle.counting.title': 'गिनती',
    'home.lifecycle.counting.description': 'वोट एकत्र होते हैं और अखंडता जांच लगातार लागू रहती है।',
    'home.lifecycle.audited.title': 'ऑडिटेड',
    'home.lifecycle.audited.description': 'ऑडिट नियंत्रण अंतिम प्रकाशन से पहले परिणाम सत्यापित करते हैं।',
    'home.lifecycle.published.title': 'प्रकाशित',
    'home.lifecycle.published.description': 'चुनाव परिणाम और पारदर्शिता मेट्रिक्स समीक्षा के लिए जारी होते हैं।',
    'home.lifecycle.archived.title': 'आर्काइव',
    'home.lifecycle.archived.description': 'बंद चुनाव लंबे-काल रिकॉर्ड के लिए उपलब्ध रहते हैं।',
    'home.why.eyebrow': 'मतदान क्यों जरूरी है',
    'home.why.title': 'मतदान सार्वजनिक जरूरतों को लागू प्राथमिकताओं में बदलता है।',
    'home.why.body': 'चुनाव केवल एक रस्म नहीं है। यह जवाबदेही तंत्र है जो बजट, नीति, और प्रतिनिधित्व तय करता है। बेहतर भागीदारी से बेहतर संस्थान बनते हैं।',
    'home.why.point1': 'मतदान नागरिक सहमति से सार्वजनिक नेतृत्व को वैध बनाता है।',
    'home.why.point2': 'यह सार्वजनिक खर्च को वास्तविक समुदाय प्राथमिकताओं से जोड़ता है।',
    'home.why.point3': 'यह शांतिपूर्ण सत्ता हस्तांतरण और नीति निरंतरता सुनिश्चित करता है।',
    'home.evolution.eyebrow': 'प्लेटफॉर्म विकास',
    'home.evolution.title': 'एक बैलट से बहु-चुनाव संचालन तक।',
    'home.evolution.body': 'परिपक्व वोटिंग प्लेटफॉर्म वोटर के लिए friction घटाता है और नियामकों, पर्यवेक्षकों, और प्रशासकों के लिए भरोसा बढ़ाता है।',
    'home.evolution.point1': 'हर चुनाव में प्रति यूजर एक वोट और अलग रसीद रिकॉर्ड।',
    'home.evolution.point2': 'चुनाव-विशिष्ट उम्मीदवार समूह और स्वतंत्र पारदर्शिता मेट्रिक्स।',
    'home.evolution.point3': 'ड्राफ्ट से आर्काइव तक गवर्नेंस चेकपॉइंट।',
    'home.evolution.primaryCta': 'चुनाव में जुड़ें',
    'home.evolution.secondaryCta': 'पारदर्शिता देखें',
    'vote.defaultVoter': 'नागरिक',
    'vote.eyebrow': 'आधिकारिक बैलट एरिना',
    'vote.title': 'अपना वोट डालें',
    'vote.welcome': 'स्वागत है',
    'vote.subtitle': 'एक उम्मीदवार चुनें और अपना बैलट पुष्टि करें।',
    'vote.accessibility.badge': 'सुलभता मोड सक्रिय',
    'vote.accessibility.stepperLabel': 'मतदान चरण',
    'vote.accessibility.stepStatus': 'चरण {current} / {total}',
    'vote.accessibility.instructions': 'फ़ील्ड और बटन के बीच जाने के लिए टैब का उपयोग करें। एंटर या स्पेस से सक्रिय करें।',
    'vote.accessibility.stepElection': 'चुनाव चुनें',
    'vote.accessibility.stepCandidate': 'उम्मीदवार चुनें',
    'vote.accessibility.stepVerification': 'पहचान सत्यापन',
    'vote.accessibility.stepReview': 'समीक्षा और सबमिट',
    'vote.accessibility.back': 'वापस',
    'vote.accessibility.next': 'जारी रखें',
    'vote.accessibility.candidateHint': 'एक उम्मीदवार चुनें। विकल्पों में जाने के लिए टैब का उपयोग करें।',
    'vote.accessibility.verificationHint': '6-अंकों का कोड मांगें और सत्यापित करें ताकि सबमिशन अनलॉक हो सके।',
    'vote.accessibility.reviewHint': 'अपने चयन की समीक्षा करें और मतदान शर्तें पुष्टि करें।',
    'vote.statusTitle': 'मतदान स्थिति',
    'vote.status.submitted': 'वोट पहले ही सबमिट हो चुका है',
    'vote.status.awaiting': 'आपके वोट की प्रतीक्षा है',
    'vote.selectElection': 'चुनाव चुनें',
    'vote.selectElectionPlaceholder': 'चुनाव चुनें',
    'vote.noElections': 'कोई चुनाव उपलब्ध नहीं',
    'vote.metric.candidates': 'उम्मीदवार',
    'vote.metric.votes': 'चुनाव वोट',
    'vote.metric.electionCandidates': 'चुनावी उम्मीदवार',
    'vote.loading': 'आधिकारिक बैलट डेटा लोड हो रहा है...',
    'vote.noElectionTitle': 'कोई चुनाव उपलब्ध नहीं है',
    'vote.noElectionBody': 'पहले एडमिन चुनाव बनाए, फिर मतदान सक्षम होगा।',
    'vote.loadingBallot': 'चयनित चुनाव का बैलट लोड हो रहा है...',
    'vote.noCandidatesTitle': 'कोई उम्मीदवार उपलब्ध नहीं',
    'vote.noCandidatesBody': 'इस चुनाव के लिए उम्मीदवार अभी कॉन्फिगर नहीं हुए हैं।',
    'vote.summary.title': 'वोट सारांश',
    'vote.summary.imageAlt': 'डिजिटल बैलट और सुरक्षित वोट पुष्टि',
    'vote.summary.election': 'चुनाव',
    'vote.summary.selectedCandidate': 'चयनित उम्मीदवार',
    'vote.summary.noneSelected': 'अभी तक कोई उम्मीदवार चयनित नहीं है।',
    'vote.summary.oneVote': 'एक अकाउंट प्रति चुनाव केवल एक वोट डाल सकता है। सबमिट करने से पहले चयन की समीक्षा करें।',
    'vote.verification.title': 'मजबूत वोटर सत्यापन',
    'vote.verification.body': 'एक बार इस्तेमाल होने वाला 6-अंकों का कोड मांगें, सत्यापित करें, फिर बैलट सबमिट करें।',
    'vote.verification.requesting': 'रिक्वेस्ट हो रही है...',
    'vote.verification.request': 'कोड रिक्वेस्ट करें',
    'vote.verification.placeholder': '6-अंकों का कोड',
    'vote.verification.verifying': 'सत्यापन हो रहा है...',
    'vote.verification.verify': 'कोड सत्यापित करें',
    'vote.verification.preview': 'डेव प्रीव्यू कोड',
    'vote.verification.expires': 'कोड समाप्ति समय',
    'vote.verification.active': 'इस चुनाव के लिए सत्यापन सक्रिय है।',
    'vote.terms': 'मैं पुष्टि करता/करती हूं कि यह वोट मेरा स्वतंत्र और अंतिम निर्णय है।',
    'vote.cta.submitting': 'वोट सबमिट हो रहा है...',
    'vote.cta.submitted': 'वोट पहले ही सबमिट',
    'vote.cta.notLive': 'चुनाव लाइव नहीं है',
    'vote.cta.completeVerification': 'पहले सत्यापन पूरा करें',
    'vote.cta.confirm': 'वोट पुष्टि करें',
    'vote.footerNote': 'सबमिशन प्रमाणित सत्र और एक-वोट प्रवर्तन से सुरक्षित है।',
    'vote.recorded': 'आपका वोट सफलतापूर्वक दर्ज हो गया है।',
    'vote.receipt.title': 'वोट रसीद',
    'vote.receipt.verify': 'इस रसीद को सत्यापित करें',
    'vote.errors.loadElections': 'चुनाव डेटा लोड नहीं हो सका। कृपया रिफ्रेश करें।',
    'vote.errors.loadReceipt': 'इस चुनाव के लिए रसीद स्थिति लोड नहीं हो सकी।',
    'vote.errors.loadBallot': 'इस चुनाव के लिए बैलट डेटा लोड नहीं हो सका। कृपया फिर कोशिश करें।',
    'vote.errors.selectElectionForCode': 'वेरिफिकेशन कोड मांगने से पहले चुनाव चुनें।',
    'vote.errors.verificationNotLive': 'वेरिफिकेशन केवल लाइव स्थिति में उपलब्ध है।',
    'vote.errors.alreadyVoted': 'इस चुनाव में वोट पहले ही डाला जा चुका है।',
    'vote.verification.requested': 'वेरिफिकेशन कोड सफलतापूर्वक अनुरोध किया गया।',
    'vote.errors.requestCodeFailed': 'वेरिफिकेशन कोड अनुरोध नहीं हो सका।',
    'vote.errors.invalidCode': 'मान्य 6-अंकों का वेरिफिकेशन कोड दर्ज करें।',
    'vote.verification.success': 'सत्यापन पूरा हुआ। अब आप वोट डाल सकते हैं।',
    'vote.errors.verifyFailed': 'कोड सत्यापन विफल हुआ।',
    'vote.errors.selectElection': 'वोटिंग से पहले चुनाव चुनें।',
    'vote.errors.notLive': 'यह चुनाव फिलहाल वोट स्वीकार नहीं कर रहा है।',
    'vote.errors.confirmTerms': 'जारी रखने के लिए मतदान शर्तें पुष्टि करें',
    'vote.errors.selectCandidate': 'जारी रखने के लिए एक उम्मीदवार चुनें',
    'vote.errors.completeVerification': 'वोट सबमिट करने से पहले मजबूत वोटर सत्यापन पूरा करें।',
    'vote.success': 'वोट सफलतापूर्वक सबमिट हुआ!',
    'vote.errors.submitFailed': 'वोट सबमिट नहीं हो सका। कृपया फिर कोशिश करें।',
    'vote.statusLabel': 'स्थिति',
    'election.status.unknown': 'अज्ञात',
    'election.status.draft': 'ड्राफ्ट',
    'election.status.registration': 'पंजीकरण',
    'election.status.live': 'लाइव मतदान',
    'election.status.counting': 'गिनती',
    'election.status.audited': 'ऑडिटेड',
    'election.status.published': 'प्रकाशित',
    'election.status.archived': 'आर्काइव',
    'candidates.eyebrow': 'उम्मीदवार प्रोफाइल + तुलना',
    'candidates.title': 'उम्मीदवारों को गहराई से देखें',
    'candidates.subtitle': 'सत्यापित उम्मीदवार प्रोफाइल देखें और बैलट एरिना से पहले तीन तक उम्मीदवारों की तुलना करें।',
    'candidates.electionContext': 'चुनाव संदर्भ',
    'candidates.noElections': 'कोई चुनाव उपलब्ध नहीं',
    'candidates.selectElection': 'चुनाव चुनें',
    'candidates.imageAlt': 'उम्मीदवार तुलना बोर्ड',
    'candidates.noElectionSelected': 'कोई चुनाव चयनित नहीं',
    'candidates.stats.election': 'चुनाव',
    'candidates.stats.visible': 'दिखाई देने वाले उम्मीदवार',
    'candidates.stats.parties': 'भाग लेने वाली पार्टियां',
    'candidates.stats.compareQueue': 'तुलना कतार',
    'candidates.searchPlaceholder': 'उम्मीदवार, पार्टी, क्षेत्र, या घोषणापत्र से खोजें',
    'candidates.loading': 'उम्मीदवार प्रोफाइल लोड हो रहे हैं...',
    'candidates.none': 'इस चुनाव के लिए कोई उम्मीदवार नहीं मिले।',
    'candidates.verified': 'सत्यापित',
    'candidates.profileOpen': 'प्रोफाइल खुला',
    'candidates.viewProfile': 'प्रोफाइल देखें',
    'candidates.removeCompare': 'तुलना हटाएं',
    'candidates.addCompare': 'तुलना में जोड़ें',
    'candidates.profile.title': 'उम्मीदवार प्रोफाइल',
    'candidates.profile.loading': 'प्रोफाइल लोड हो रहा है...',
    'candidates.profile.empty': 'पूरा प्रोफाइल देखने के लिए किसी उम्मीदवार को चुनें।',
    'candidates.profile.region': 'क्षेत्र',
    'candidates.profile.education': 'शिक्षा',
    'candidates.profile.experience': 'अनुभव',
    'candidates.profile.na': 'उपलब्ध नहीं',
    'candidates.compare.title': 'तुलना बोर्ड',
    'candidates.compare.reset': 'रीसेट',
    'candidates.compare.instructions': 'साइड-बाय-साइड तुलना के लिए 2 से 3 उम्मीदवार चुनें।',
    'candidates.compare.noneSelected': 'कोई उम्मीदवार चयनित नहीं है।',
    'candidates.compare.selected': 'चयनित',
    'candidates.compare.loading': 'तुलना लोड हो रही है...',
    'candidates.compare.field': 'फ़ील्ड',
    'candidates.compare.party': 'पार्टी',
    'candidates.compare.region': 'क्षेत्र',
    'candidates.compare.experience': 'अनुभव',
    'candidates.compare.priorities': 'प्राथमिकताएं',
    'candidates.compare.empty': 'कम से कम 2 उम्मीदवार चुनने पर तुलना तालिका दिखेगी।',
    'candidates.compare.cta': 'बैलट पर जाएं',
    'candidates.region.district': '{region} जिला',
    'candidates.region.national': 'राष्ट्रीय नागरिक जिला',
    'candidates.experience.double': '{area1} और {area2} में नीति नेतृत्व',
    'candidates.experience.single': '{area} में नीति नेतृत्व',
    'candidates.experience.default': 'लोक प्रशासन और नागरिक नीति नेतृत्व',
    'candidates.priorities.citizenService': 'नागरिक सेवा वितरण',
    'candidates.priorities.accountability': 'नीति जवाबदेही',
    'candidates.priorities.transparent': 'पारदर्शी गवर्नेंस',
    'candidates.errors.loadElections': 'चुनाव लोड नहीं हो सके। कृपया फिर कोशिश करें।',
    'candidates.errors.loadCandidates': 'इस चुनाव के लिए उम्मीदवार प्रोफाइल लोड नहीं हो सके। कृपया फिर कोशिश करें।',
    'candidates.errors.compareFailed': 'तुलना डेटा लोड नहीं हो सका।',
    'candidates.errors.compareLimit': 'आप एक समय में अधिकतम 3 उम्मीदवारों की तुलना कर सकते हैं।',
    'transparency.errors.load': 'फिलहाल पारदर्शिता डैशबोर्ड लोड नहीं हो सका।',
    'transparency.eyebrow': 'सार्वजनिक पारदर्शिता डैशबोर्ड',
    'transparency.title': 'खुले चुनाव मेट्रिक्स',
    'transparency.subtitle': 'टर्नआउट, उम्मीदवार रैंकिंग, पार्टी वोट शेयर और रसीद स्तर की सत्यापन गतिविधि का रियल-टाइम दृश्य।',
    'transparency.scope': 'चुनाव स्कोप',
    'transparency.noElections': 'कोई चुनाव उपलब्ध नहीं',
    'transparency.selectElection': 'चुनाव चुनें',
    'transparency.metrics.parties': 'पार्टियां',
    'transparency.metrics.ranked': 'रैंक किए उम्मीदवार',
    'transparency.metrics.receipts': 'हाल की रसीदें',
    'transparency.imageAlt': 'चुनाव पारदर्शिता एनालिटिक्स',
    'transparency.loading': 'पारदर्शिता मेट्रिक्स लोड हो रहे हैं...',
    'transparency.empty': 'पारदर्शिता एनालिटिक्स के लिए अभी कोई चुनाव उपलब्ध नहीं है।',
    'transparency.table.election': 'चुनाव',
    'transparency.table.registered': 'पंजीकृत वोटर',
    'transparency.table.votes': 'कुल वोट',
    'transparency.table.turnout': 'टर्नआउट',
    'transparency.table.parties': 'सक्रिय पार्टियां',
    'transparency.results.title': 'चुनाव परिणाम गणना',
    'transparency.results.subtitle': 'हर चुनाव के शीर्ष 3 उम्मीदवार और कुल वोट डायनेमिक ट्रैकिंग के लिए दिखाए जाते हैं।',
    'transparency.results.empty': 'अभी कोई परिणाम डेटा उपलब्ध नहीं है।',
    'transparency.results.totalVotes': 'कुल वोट',
    'transparency.results.rank': 'रैंक',
    'transparency.results.candidate': 'उम्मीदवार',
    'transparency.results.party': 'पार्टी',
    'transparency.results.votes': 'वोट',
    'transparency.chart.partyShare': 'पार्टी वोट शेयर',
    'transparency.chart.empty': 'पार्टी वोट शेयर डेटा उपलब्ध नहीं है।',
    'transparency.chart.votes': 'वोट',
    'transparency.timeline.title': 'टर्नआउट टाइमलाइन',
    'transparency.timeline.empty': 'अभी कोई टर्नआउट इवेंट रिकॉर्ड नहीं हुआ है।',
    'login.eyebrow': 'सुरक्षित साइन इन',
    'login.title': 'वापसी पर स्वागत है',
    'login.subtitle': 'अपना सत्यापित बैलट एक्सेस करें और आधिकारिक निर्णयों में भाग लें।',
    'login.badge.jwt': 'JWT सत्र',
    'login.badge.oneVote': 'एक वोट / चुनाव',
    'login.badge.receipt': 'रसीद आधारित',
    'login.emailLabel': 'ईमेल पता',
    'login.emailPlaceholder': 'you@example.com',
    'login.passwordLabel': 'पासवर्ड',
    'login.passwordPlaceholder': 'अपना सुरक्षित पासवर्ड दर्ज करें',
    'login.loading': 'साइन इन हो रहा है...',
    'login.cta': 'साइन इन',
    'login.noAccount': 'नए वोटर?',
    'login.createAccount': 'अकाउंट बनाएं',
    'login.imageAlt': 'शील्ड और लॉक सुरक्षा के साथ वोटर लॉगिन',
    'login.assuranceEyebrow': 'प्लेटफॉर्म आश्वासन',
    'login.assuranceTitle': 'चुनाव-स्तरीय एक्सेस नियंत्रण',
    'login.assuranceBody': 'सत्र सुरक्षा, टोकन-आधारित प्रमाणीकरण, और एक-वोट नियम संस्थागत भरोसा बनाए रखते हैं।',
    'login.assurance.identityTitle': 'पहचान सत्यापन',
    'login.assurance.identityBody': 'केवल प्रमाणित उपयोगकर्ता बैलट इंटरफेस तक पहुंच सकते हैं।',
    'login.assurance.sessionTitle': 'सत्र सुरक्षा',
    'login.assurance.sessionBody': 'प्रमाणित स्थिति पूरे ऐप में नियंत्रित पहुंच के लिए सिंक रहती है।',
    'login.assurance.readyTitle': 'गवर्नेंस तैयार',
    'login.assurance.readyBody': 'विश्वसनीय सार्वजनिक भागीदारी के लिए परिष्कृत नागरिक अनुभव।',
    'login.success': 'लॉगिन सफल! रीडायरेक्ट हो रहा है...',
    'login.error': 'लॉगिन विफल। कृपया फिर कोशिश करें।',
    'signup.eyebrow': 'सत्यापित पंजीकरण',
    'signup.title': 'वोटर अकाउंट बनाएं',
    'signup.subtitle': 'एक बार रजिस्टर करें और आधिकारिक डिजिटल बैलट व गवर्नेंस डैशबोर्ड एक्सेस करें।',
    'signup.badge.identity': 'पहचान तैयार',
    'signup.badge.credential': 'सुरक्षित क्रेडेंशियल',
    'signup.badge.access': 'तत्काल बैलट एक्सेस',
    'signup.nameLabel': 'पूरा नाम',
    'signup.namePlaceholder': 'आपका कानूनी नाम',
    'signup.emailLabel': 'ईमेल पता',
    'signup.emailPlaceholder': 'you@example.com',
    'signup.passwordLabel': 'पासवर्ड',
    'signup.passwordPlaceholder': 'कम से कम 6 अक्षर',
    'signup.confirmLabel': 'पासवर्ड पुष्टि',
    'signup.confirmPlaceholder': 'पासवर्ड फिर से दर्ज करें',
    'signup.loading': 'अकाउंट बनाया जा रहा है...',
    'signup.cta': 'अकाउंट बनाएं',
    'signup.haveAccount': 'पहले से पंजीकृत हैं?',
    'signup.signInLink': 'यहां साइन इन करें',
    'signup.imageAlt': 'वोटिंग प्लेटफॉर्म के लिए नागरिक ऑनबोर्डिंग और पहचान सत्यापन',
    'signup.onboardingEyebrow': 'ऑनबोर्डिंग मानक',
    'signup.onboardingTitle': 'विश्वसनीय नागरिक ऑनबोर्डिंग',
    'signup.onboardingBody': 'परिपक्व वोटिंग इकोसिस्टम साफ पंजीकरण, पहचान भरोसा, और धोखाधड़ी-रोधी अकाउंट निर्माण से शुरू होता है।',
    'signup.onboarding.identityTitle': 'नागरिक पहचान तैयार',
    'signup.onboarding.identityBody': 'उपयोगकर्ता बैलट एक्सेस से पहले ऑनबोर्ड होते हैं।',
    'signup.onboarding.credentialsTitle': 'सुरक्षित क्रेडेंशियल',
    'signup.onboarding.credentialsBody': 'अकाउंट निर्माण से पहले पासवर्ड सत्यापित किए जाते हैं।',
    'signup.onboarding.ballotTitle': 'सीधा बैलट एक्सेस',
    'signup.onboarding.ballotBody': 'पंजीकरण के बाद उपयोगकर्ता सीधे सुरक्षित वोटिंग एरिना में जाते हैं।',
    'signup.onboarding.integrityTitle': 'प्लेटफॉर्म अखंडता',
    'signup.onboarding.integrityBody': 'विश्वसनीय ऑनबोर्डिंग चुनाव विश्वसनीयता की पहली परत है।',
    'signup.success': 'अकाउंट सफलतापूर्वक बना! रीडायरेक्ट हो रहा है...',
    'signup.errors.passwordMismatch': 'पासवर्ड मेल नहीं खाते',
    'signup.errors.passwordLength': 'पासवर्ड कम से कम 6 अक्षर का होना चाहिए',
    'signup.errors.submitFailed': 'पंजीकरण विफल। कृपया फिर कोशिश करें।',
    'common.cancel': 'रद्द करें',
    'common.delete': 'हटाएं',
    'common.edit': 'संपादित करें',
    'common.refresh': 'रीफ्रेश',
    'common.na': 'उपलब्ध नहीं',
    'common.ellipsis': '...',
    'manage.errors.loadCandidates': 'उम्मीदवार प्रबंधन डेटा लोड नहीं हो सका।',
    'manage.errors.adminOnly': 'उम्मीदवार और चुनाव प्रबंधन केवल एडमिन खातों के लिए है।',
    'manage.errors.loadAdmin': 'एडमिन प्रबंधन डेटा लोड नहीं हो सका।',
    'manage.errors.candidateAdminOnly': 'उम्मीदवार प्रबंधन केवल एडमिन खातों के लिए है।',
    'manage.errors.selectElectionForCandidate': 'उम्मीदवार प्रबंधन से पहले एक चुनाव चुनें।',
    'manage.errors.candidateRequiredFields': 'नाम, पार्टी और घोषणापत्र आवश्यक हैं।',
    'manage.toast.candidateUpdated': 'उम्मीदवार सफलतापूर्वक अपडेट हुआ।',
    'manage.toast.candidateCreated': 'उम्मीदवार सफलतापूर्वक बनाया गया।',
    'manage.errors.saveCandidate': 'उम्मीदवार सहेजने में विफल।',
    'manage.toast.candidateDeleted': 'उम्मीदवार सफलतापूर्वक हटाया गया।',
    'manage.errors.deleteCandidate': 'उम्मीदवार हटाने में विफल।',
    'manage.errors.electionAdminOnly': 'चुनाव प्रबंधन केवल एडमिन खातों के लिए है।',
    'manage.errors.electionNameRequired': 'चुनाव का नाम आवश्यक है।',
    'manage.toast.electionUpdated': 'चुनाव सफलतापूर्वक अपडेट हुआ।',
    'manage.toast.electionCreated': 'चुनाव सफलतापूर्वक बनाया गया।',
    'manage.errors.saveElection': 'चुनाव सहेजने में विफल।',
    'manage.toast.electionTransition': 'चुनाव को {status} चरण में ले जाया गया।',
    'manage.errors.transitionElection': 'चुनाव स्थिति बदलने में विफल।',
    'manage.modal.deleteCandidateTitle': 'उम्मीदवार हटाएं',
    'manage.modal.deleteCandidateBody': 'क्या आप इस उम्मीदवार को हटाना चाहते हैं? यह कार्रवाई वापस नहीं ली जा सकती।',
    'manage.header.eyebrow': 'चुनाव + उम्मीदवार प्रबंधन',
    'manage.header.title': 'चुनाव लाइफसाइकिल संचालन चलाएं',
    'manage.header.subtitle': 'चुनाव बनाएं, लाइफसाइकिल स्टेट बदलें, और हर चुनाव के अनुसार उम्मीदवार रिकॉर्ड प्रबंधित करें।',
    'manage.metrics.totalElections': 'कुल चुनाव',
    'manage.metrics.liveElections': 'लाइव चुनाव',
    'manage.metrics.registeredCandidates': 'पंजीकृत उम्मीदवार',
    'manage.metrics.trackedVotes': 'ट्रैक किए गए वोट',
    'manage.state.loadingWorkspace': 'एडमिन प्रबंधन वर्कस्पेस लोड हो रहा है...',
    'manage.state.restrictedTitle': 'प्रतिबंधित एक्सेस',
    'manage.state.restrictedBody': 'चुनाव और उम्मीदवार प्रबंधन केवल एडमिन खातों के लिए उपलब्ध है।',
    'manage.elections.title': 'चुनाव लाइफसाइकिल स्टूडियो',
    'manage.elections.form.name': 'चुनाव नाम',
    'manage.elections.form.namePlaceholder': 'राष्ट्रीय आम चुनाव 2027',
    'manage.elections.form.description': 'विवरण',
    'manage.elections.form.descriptionPlaceholder': 'वैकल्पिक चुनाव विवरण',
    'manage.elections.form.registrationStarts': 'पंजीकरण शुरू',
    'manage.elections.form.registrationEnds': 'पंजीकरण समाप्त',
    'manage.elections.form.votingStarts': 'मतदान शुरू',
    'manage.elections.form.votingEnds': 'मतदान समाप्त',
    'manage.elections.form.update': 'चुनाव अपडेट करें',
    'manage.elections.form.create': 'चुनाव बनाएं',
    'manage.elections.form.cancelEdit': 'एडिट रद्द करें',
    'manage.elections.empty': 'अभी तक कोई चुनाव नहीं बना है।',
    'manage.elections.card.status': 'स्थिति: {status}',
    'manage.elections.card.stats': 'उम्मीदवार: {candidates} | वोट: {votes}',
    'manage.elections.card.selected': 'चयनित',
    'manage.elections.card.select': 'चुनें',
    'manage.elections.card.transitioning': 'बदल रहा है...',
    'manage.elections.card.moveTo': '{status} पर ले जाएं',
    'manage.candidates.title': 'उम्मीदवार स्टूडियो',
    'manage.candidates.activeElection': 'सक्रिय चुनाव',
    'manage.candidates.noElections': 'कोई चुनाव उपलब्ध नहीं',
    'manage.candidates.selectElection': 'चुनाव चुनें',
    'manage.candidates.lifecycle': 'लाइफसाइकिल: {status}',
    'manage.candidates.form.name': 'उम्मीदवार नाम',
    'manage.candidates.form.namePlaceholder': 'पूरा नाम',
    'manage.candidates.form.party': 'पार्टी',
    'manage.candidates.form.partyPlaceholder': 'पार्टी का नाम',
    'manage.candidates.form.tagline': 'अभियान टैगलाइन',
    'manage.candidates.form.taglinePlaceholder': 'छोटी अभियान लाइन',
    'manage.candidates.form.region': 'क्षेत्र',
    'manage.candidates.form.regionPlaceholder': 'क्षेत्र या जिला',
    'manage.candidates.form.experience': 'अनुभव',
    'manage.candidates.form.experiencePlaceholder': 'अनुभव सारांश',
    'manage.candidates.form.imageUrl': 'इमेज URL',
    'manage.candidates.form.imageUrlPlaceholder': 'https://example.com/candidate.jpg',
    'manage.candidates.form.manifesto': 'घोषणापत्र',
    'manage.candidates.form.manifestoPlaceholder': 'उम्मीदवार घोषणापत्र',
    'manage.candidates.form.priorities': 'प्राथमिकताएं (कॉमा से अलग)',
    'manage.candidates.form.prioritiesPlaceholder': 'स्वास्थ्य, शिक्षा, परिवहन',
    'manage.candidates.form.update': 'उम्मीदवार अपडेट करें',
    'manage.candidates.form.add': 'उम्मीदवार जोड़ें',
    'manage.candidates.form.cancelEdit': 'एडिट रद्द करें',
    'manage.candidates.loading': 'उम्मीदवार लोड हो रहे हैं...',
    'manage.candidates.empty': 'इस चुनाव के लिए अभी उम्मीदवार उपलब्ध नहीं हैं।',
    'manage.candidates.card.votes': 'वोट: {count}',
    'disputes.status.open': 'खुला',
    'disputes.status.underReview': 'समीक्षा में',
    'disputes.status.resolved': 'समाधान हुआ',
    'disputes.status.rejected': 'अस्वीकृत',
    'disputes.type.recount': 'पुनर्गणना',
    'disputes.type.dispute': 'विवाद',
    'disputes.form.type.disputeCase': 'विवाद केस',
    'disputes.form.type.recountRequest': 'पुनर्गणना अनुरोध',
    'disputes.filters.status.all': 'सभी स्थितियां',
    'disputes.filters.type.all': 'सभी प्रकार',
    'disputes.errors.bootstrap': 'फिलहाल पुनर्गणना और विवाद मॉड्यूल लोड नहीं हो सका।',
    'disputes.errors.loadMyCases': 'आपके विवाद रिकॉर्ड लोड नहीं हो सके।',
    'disputes.errors.loadAdminCases': 'एडमिन विवाद कतार लोड नहीं हो सकी।',
    'disputes.errors.selectElection': 'केस दर्ज करने से पहले एक चुनाव चुनें।',
    'disputes.errors.subjectLength': 'विषय कम से कम 8 अक्षर का होना चाहिए।',
    'disputes.errors.descriptionLength': 'विवरण कम से कम 20 अक्षर का होना चाहिए।',
    'disputes.errors.recountNeedsEvidence': 'पुनर्गणना अनुरोध के लिए रसीद कोड या उम्मीदवार चयन आवश्यक है।',
    'disputes.toast.caseSubmitted': 'केस सफलतापूर्वक सबमिट हुआ।',
    'disputes.errors.submitCase': 'विवाद केस सबमिट करने में विफल।',
    'disputes.errors.resolutionNoteLength': 'अंतिम अपडेट के लिए समाधान नोट में कम से कम 10 अक्षर जोड़ें।',
    'disputes.toast.caseStatusUpdated': 'केस को {status} के रूप में मार्क किया गया।',
    'disputes.errors.updateStatus': 'केस स्थिति अपडेट नहीं हो सकी।',
    'disputes.header.eyebrow': 'पुनर्गणना और विवाद मॉड्यूल',
    'disputes.header.title': 'चुनाव केस प्रबंधन',
    'disputes.header.subtitle': 'पुनर्गणना अनुरोध और अखंडता विवाद अलग वर्कफ़्लो में दर्ज करें, फिर केस समीक्षा और परिणाम ट्रैक करें।',
    'disputes.imageAlt': 'विवाद समाधान डैशबोर्ड चित्रण',
    'disputes.metrics.role': 'भूमिका: {role}',
    'disputes.metrics.totalCases': 'चुनाव केस: {count}',
    'disputes.metrics.currentElection': 'वर्तमान चुनाव: {name}',
    'disputes.metrics.notSelected': 'चयनित नहीं',
    'disputes.state.loadingModule': 'मॉड्यूल लोड हो रहा है...',
    'disputes.filters.electionScope': 'चुनाव स्कोप',
    'disputes.filters.noElections': 'कोई चुनाव उपलब्ध नहीं',
    'disputes.filters.selectElection': 'चुनाव चुनें',
    'disputes.filters.status.label': 'स्थिति फ़िल्टर',
    'disputes.filters.type.label': 'प्रकार फ़िल्टर',
    'disputes.form.title': 'नया केस दर्ज करें',
    'disputes.form.type.label': 'केस प्रकार',
    'disputes.form.candidate.label': 'उम्मीदवार (वैकल्पिक)',
    'disputes.form.candidate.placeholder': 'उम्मीदवार चुनें',
    'disputes.form.subject.label': 'विषय',
    'disputes.form.subject.placeholder': 'उदाहरण: रसीद mismatch के लिए पुनर्गणना अनुरोध',
    'disputes.form.receipt.label': 'रसीद कोड (वैकल्पिक)',
    'disputes.form.receipt.placeholder': 'CV-2026-AB12EF',
    'disputes.form.description.label': 'विवरण',
    'disputes.form.description.placeholder': 'क्या हुआ, पुनर्गणना या जांच क्यों आवश्यक है, और समयरेखा विवरण लिखें।',
    'disputes.form.candidate.linked': 'इस केस से जुड़ा उम्मीदवार:',
    'disputes.form.submitting': 'सबमिट हो रहा है...',
    'disputes.form.submit': 'केस सबमिट करें',
    'disputes.myCases.title': 'मेरे केस',
    'disputes.myCases.loading': 'आपके केस लोड हो रहे हैं...',
    'disputes.myCases.empty': 'चुने गए चुनाव के लिए कोई केस रिकॉर्ड नहीं मिला।',
    'disputes.myCases.type': 'प्रकार: {type}',
    'disputes.myCases.receipt': 'रसीद: {code}',
    'disputes.myCases.filed': 'दर्ज: {date}',
    'disputes.myCases.resolutionNote': 'समाधान नोट',
    'disputes.admin.title': 'एडमिन समीक्षा कतार',
    'disputes.admin.refresh': 'कतार रीफ्रेश करें',
    'disputes.admin.loading': 'एडमिन कतार लोड हो रही है...',
    'disputes.admin.empty': 'चुने गए फ़िल्टर से कोई विवाद केस नहीं मिला।',
    'disputes.admin.filedBy': '{election} | दर्जकर्ता {name}',
    'disputes.admin.filedByFallback': 'मतदाता',
    'disputes.admin.resolutionPlaceholder': 'जांच निष्कर्ष या अंतिम समाधान नोट जोड़ें',
    'disputes.admin.actions.underReview': 'समीक्षा में चिन्हित करें',
    'disputes.admin.actions.resolve': 'समाधान करें',
    'disputes.admin.actions.reject': 'अस्वीकार करें',
    'disputes.notes.title': 'वर्कफ़्लो नोट्स',
    'disputes.notes.item1': 'बैलट अखंडता, पात्रता, या सिस्टम व्यवहार मुद्दों के लिए विवाद का उपयोग करें।',
    'disputes.notes.item2': 'जब गिनती भरोसे के लिए उम्मीदवार- या रसीद-लिंक समीक्षा चाहिए तो पुनर्गणना का उपयोग करें।',
    'disputes.notes.item3': 'केस स्थिति खुला से समीक्षा में, फिर समाधान या अस्वीकृत तक अपडेट होती है।',
    'disputes.notes.item4': 'अंतिम नोट्स और कार्रवाइयाँ My Cases पैनल में ट्रैक करें।',
    'disputes.notes.footer': 'केस रिकॉर्ड पारदर्शी ऑडिटिंग के लिए चुनाव स्कोप से जुड़े हैं।',
    'receipt.header.eyebrow': 'वोट रसीद सत्यापन',
    'receipt.header.title': 'वोट अखंडता सत्यापित करें',
    'receipt.header.subtitle': 'वोट सबमिशन पर बने रसीद कोड को दर्ज करके चुनाव लेजर में वोट रसीद की पुष्टि करें।',
    'receipt.header.imageAlt': 'वोट रसीद सत्यापन डैशबोर्ड',
    'receipt.metrics.ledgerSearch': 'लेजर खोज',
    'receipt.metrics.electionScoped': 'चुनाव-स्कोप्ड',
    'receipt.metrics.pdfExport': 'PDF निर्यात',
    'receipt.controls.placeholder': 'रसीद कोड दर्ज करें (जैसे, CV-2026-AB12EF)',
    'receipt.controls.verifying': 'सत्यापित हो रहा है...',
    'receipt.controls.verify': 'सत्यापित करें',
    'receipt.controls.exportPdf': 'PDF निर्यात करें',
    'receipt.controls.electionScope': 'चुनाव स्कोप (मेरी रसीद के लिए)',
    'receipt.controls.noElections': 'कोई चुनाव उपलब्ध नहीं',
    'receipt.controls.selectElection': 'चुनाव चुनें',
    'receipt.controls.exportHint': 'वोटर विवरण और कम से कम एक रसीद रिकॉर्ड लोड होने पर निर्यात उपलब्ध होगा।',
    'receipt.myReceipt.title': 'मेरी रसीद',
    'receipt.myReceipt.loading': 'आपकी रसीद लोड हो रही है...',
    'receipt.myReceipt.cardTitle': 'प्रमाणित मतदाता रसीद',
    'receipt.myReceipt.empty': 'अपनी व्यक्तिगत रसीद कोड बनाने के लिए साइन इन करें और वोट डालें।',
    'receipt.verify.title': 'सत्यापन परिणाम',
    'receipt.verify.loading': 'लेजर में रसीद सत्यापित हो रही है...',
    'receipt.verify.success': 'रसीद सफलतापूर्वक सत्यापित हुई',
    'receipt.verify.cardTitle': 'लेजर सत्यापन',
    'receipt.verify.empty': 'वोट सबमिशन स्थिति सत्यापित करने के लिए रसीद कोड दर्ज करें।',
    'receipt.card.code': 'रसीद कोड',
    'receipt.card.status': 'स्थिति',
    'receipt.card.submitted': 'सबमिट समय',
    'receipt.card.candidate': 'उम्मीदवार',
    'receipt.card.candidateMissing': 'उम्मीदवार उपलब्ध नहीं',
    'receipt.errors.fetchMine': 'फिलहाल आपकी रसीद नहीं मिल सकी।',
    'receipt.errors.invalidCode': 'कृपया एक मान्य रसीद कोड दर्ज करें।',
    'receipt.errors.verifyFailed': 'फिलहाल रसीद सत्यापित नहीं हो सकी।',
    'receipt.pdf.notAvailable': 'उपलब्ध नहीं',
    'receipt.pdf.portalTitle': 'SecureVote चुनाव पोर्टल',
    'receipt.pdf.issued': 'दस्तावेज़ जारी: {date}',
    'receipt.pdf.reportTitle': 'वोट अखंडता निर्यात रिपोर्ट',
    'receipt.pdf.voterDetails': 'मतदाता विवरण',
    'receipt.pdf.name': 'नाम: {name}',
    'receipt.pdf.email': 'ईमेल: {email}',
    'receipt.pdf.role': 'भूमिका: {role}',
    'receipt.pdf.roleFallback': 'मतदाता',
    'receipt.pdf.votingStatus': 'मतदान स्थिति: {status}',
    'receipt.pdf.voteCast': 'वोट डाला गया',
    'receipt.pdf.notCast': 'अभी वोट नहीं डाला',
    'receipt.pdf.voteReceiptDetails': 'वोट / रसीद विवरण',
    'receipt.pdf.election': 'चुनाव: {name}',
    'receipt.pdf.receiptCode': 'रसीद कोड: {code}',
    'receipt.pdf.receiptStatus': 'रसीद स्थिति: {status}',
    'receipt.pdf.submittedAt': 'सबमिट समय: {date}',
    'receipt.pdf.candidate': 'उम्मीदवार: {name}',
    'receipt.pdf.candidateMissing': 'उम्मीदवार उपलब्ध नहीं',
    'receipt.pdf.footer': 'यह रिपोर्ट वोट अखंडता डैशबोर्ड से बनाई गई है और रिकॉर्ड रखने के लिए है।'
  }
};

const getInitialPreferences = () => {
  const fallback = {
    language: 'en',
    theme: 'light',
    accessibilityMode: false
  };

  if (typeof window === 'undefined') {
    return fallback;
  }

  const raw = window.localStorage.getItem(STORAGE_KEY);

  if (!raw) {
    return fallback;
  }

  try {
    const parsed = JSON.parse(raw);

    return {
      language: parsed.language === 'hi' ? 'hi' : 'en',
      theme: parsed.theme === 'dark' ? 'dark' : 'light',
      accessibilityMode: Boolean(parsed.accessibilityMode)
    };
  } catch {
    return fallback;
  }
};

export const UiPreferencesProvider = ({ children }) => {
  const [preferences, setPreferences] = useState(getInitialPreferences);

  useEffect(() => {
    if (typeof window === 'undefined') {
      return;
    }

    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(preferences));

    document.documentElement.lang = preferences.language;
    document.body.classList.toggle('theme-dark', preferences.theme === 'dark');
    document.body.classList.toggle('accessibility-mode', preferences.accessibilityMode);
  }, [preferences]);

  const setLanguage = useCallback((language) => {
    setPreferences((current) => ({
      ...current,
      language: language === 'hi' ? 'hi' : 'en'
    }));
  }, []);

  const toggleTheme = useCallback(() => {
    setPreferences((current) => ({
      ...current,
      theme: current.theme === 'dark' ? 'light' : 'dark'
    }));
  }, []);

  const toggleAccessibilityMode = useCallback(() => {
    setPreferences((current) => ({
      ...current,
      accessibilityMode: !current.accessibilityMode
    }));
  }, []);

  const t = useCallback((key, fallback = '') => {
    const table = TRANSLATIONS[preferences.language] || TRANSLATIONS.en;
    return table[key] || fallback || key;
  }, [preferences.language]);

  const value = useMemo(() => ({
    language: preferences.language,
    theme: preferences.theme,
    accessibilityMode: preferences.accessibilityMode,
    setLanguage,
    toggleTheme,
    toggleAccessibilityMode,
    t
  }), [preferences, setLanguage, toggleTheme, toggleAccessibilityMode, t]);

  return (
    <UiPreferencesContext.Provider value={value}>
      {children}
    </UiPreferencesContext.Provider>
  );
};
